//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Input/InputManager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputManager : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputManager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputManager"",
    ""maps"": [
        {
            ""name"": ""Active"",
            ""id"": ""8f5756c7-35b9-47e4-b64c-1672081628d3"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a428cf53-8778-4651-bc22-c11cb655f940"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d1d1bb99-9619-4b56-836c-7bce914e00d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpRelease"",
                    ""type"": ""Value"",
                    ""id"": ""84ace4c5-28df-4f71-b42f-5c8bf962797a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlaceTrap"",
                    ""type"": ""Button"",
                    ""id"": ""86a3625d-5748-4ee1-b1ac-c01965c1fa98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""1"",
                    ""type"": ""Button"",
                    ""id"": ""b7889abd-a26a-4ab8-80da-42096b35650a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2"",
                    ""type"": ""Button"",
                    ""id"": ""f5f65078-f4df-4040-908d-395925905a5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3"",
                    ""type"": ""Button"",
                    ""id"": ""13cb7e4c-5066-429c-820f-f3e043589697"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4"",
                    ""type"": ""Button"",
                    ""id"": ""35759abc-b519-4879-a536-cf2bb0613895"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""5"",
                    ""type"": ""Button"",
                    ""id"": ""acf90332-deac-4b33-98dc-563492e18482"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""6"",
                    ""type"": ""Button"",
                    ""id"": ""ba713665-879e-4020-ad9b-8693b4ee889e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""7"",
                    ""type"": ""Button"",
                    ""id"": ""f38e7a93-ab0d-4de4-8188-7c070b78f15d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""8"",
                    ""type"": ""Button"",
                    ""id"": ""3f1a84ad-9c40-493c-a3f6-7cf333ac1e4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""9"",
                    ""type"": ""Button"",
                    ""id"": ""856f8ace-edbe-4b9e-af64-357e0298ff96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""2c68665a-a14d-4061-8b53-ca3b9054ece3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""37924b0d-85ef-4eb5-9b59-d777bd31b903"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bb3c88bb-6401-45bd-b146-2b3ad9c5406e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""46f35f40-94a1-4194-90d5-3e112b6d9eb4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d05398da-a394-4e7d-9d1a-382807a90f4a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""469367d3-a84d-4dbe-89bc-d0ed6be13e29"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""18002ad2-2c21-4442-931f-8b5cf042f39f"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9b350636-bf67-485b-88f1-eec46fd0d712"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cce8c03a-2899-411a-a37c-d914c886a9a2"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7463dd88-5a1e-4088-bbf5-490306ee2fcf"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7b37eba5-d058-4944-ba82-e3544832547f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d37fc84-f223-464d-afd2-1db77ff4a2a3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d56a9922-b1af-4b69-8659-60bc806eec71"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7c7b8d9-ab23-4c01-b6f7-d687098c7fb9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16e56dca-cf31-4046-aa5f-197c7fdb4f1f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceTrap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4466db2a-8233-4526-9558-1d86e01dfdf6"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceTrap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe694005-9ca7-4fca-888e-f803420488ab"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ca7803e-c638-4d58-8766-4850e18b7a71"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbe463d2-9449-480f-b676-5bbeb16cd508"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3fd0dae-1494-4e13-8480-ef50ae05c0c4"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f833e52-58b3-4567-b664-43c7d77f114c"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""779c10fb-65fb-4369-8949-1b353744697f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96f4486f-8ab0-4549-bcf0-30c282d89be0"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9e8f248-fddc-4c48-834b-4e4947916a16"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a9ed48c-583e-475b-b201-ec614c2a322f"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Active
        m_Active = asset.FindActionMap("Active", throwIfNotFound: true);
        m_Active_Move = m_Active.FindAction("Move", throwIfNotFound: true);
        m_Active_Jump = m_Active.FindAction("Jump", throwIfNotFound: true);
        m_Active_JumpRelease = m_Active.FindAction("JumpRelease", throwIfNotFound: true);
        m_Active_PlaceTrap = m_Active.FindAction("PlaceTrap", throwIfNotFound: true);
        m_Active__1 = m_Active.FindAction("1", throwIfNotFound: true);
        m_Active__2 = m_Active.FindAction("2", throwIfNotFound: true);
        m_Active__3 = m_Active.FindAction("3", throwIfNotFound: true);
        m_Active__4 = m_Active.FindAction("4", throwIfNotFound: true);
        m_Active__5 = m_Active.FindAction("5", throwIfNotFound: true);
        m_Active__6 = m_Active.FindAction("6", throwIfNotFound: true);
        m_Active__7 = m_Active.FindAction("7", throwIfNotFound: true);
        m_Active__8 = m_Active.FindAction("8", throwIfNotFound: true);
        m_Active__9 = m_Active.FindAction("9", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Active
    private readonly InputActionMap m_Active;
    private IActiveActions m_ActiveActionsCallbackInterface;
    private readonly InputAction m_Active_Move;
    private readonly InputAction m_Active_Jump;
    private readonly InputAction m_Active_JumpRelease;
    private readonly InputAction m_Active_PlaceTrap;
    private readonly InputAction m_Active__1;
    private readonly InputAction m_Active__2;
    private readonly InputAction m_Active__3;
    private readonly InputAction m_Active__4;
    private readonly InputAction m_Active__5;
    private readonly InputAction m_Active__6;
    private readonly InputAction m_Active__7;
    private readonly InputAction m_Active__8;
    private readonly InputAction m_Active__9;
    public struct ActiveActions
    {
        private @InputManager m_Wrapper;
        public ActiveActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Active_Move;
        public InputAction @Jump => m_Wrapper.m_Active_Jump;
        public InputAction @JumpRelease => m_Wrapper.m_Active_JumpRelease;
        public InputAction @PlaceTrap => m_Wrapper.m_Active_PlaceTrap;
        public InputAction @_1 => m_Wrapper.m_Active__1;
        public InputAction @_2 => m_Wrapper.m_Active__2;
        public InputAction @_3 => m_Wrapper.m_Active__3;
        public InputAction @_4 => m_Wrapper.m_Active__4;
        public InputAction @_5 => m_Wrapper.m_Active__5;
        public InputAction @_6 => m_Wrapper.m_Active__6;
        public InputAction @_7 => m_Wrapper.m_Active__7;
        public InputAction @_8 => m_Wrapper.m_Active__8;
        public InputAction @_9 => m_Wrapper.m_Active__9;
        public InputActionMap Get() { return m_Wrapper.m_Active; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActiveActions set) { return set.Get(); }
        public void SetCallbacks(IActiveActions instance)
        {
            if (m_Wrapper.m_ActiveActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_ActiveActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_ActiveActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.OnJump;
                @JumpRelease.started -= m_Wrapper.m_ActiveActionsCallbackInterface.OnJumpRelease;
                @JumpRelease.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.OnJumpRelease;
                @JumpRelease.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.OnJumpRelease;
                @PlaceTrap.started -= m_Wrapper.m_ActiveActionsCallbackInterface.OnPlaceTrap;
                @PlaceTrap.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.OnPlaceTrap;
                @PlaceTrap.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.OnPlaceTrap;
                @_1.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_1;
                @_1.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_1;
                @_1.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_1;
                @_2.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_2;
                @_2.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_2;
                @_2.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_2;
                @_3.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_3;
                @_3.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_3;
                @_3.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_3;
                @_4.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_4;
                @_4.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_4;
                @_4.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_4;
                @_5.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_5;
                @_5.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_5;
                @_5.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_5;
                @_6.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_6;
                @_6.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_6;
                @_6.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_6;
                @_7.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_7;
                @_7.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_7;
                @_7.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_7;
                @_8.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_8;
                @_8.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_8;
                @_8.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_8;
                @_9.started -= m_Wrapper.m_ActiveActionsCallbackInterface.On_9;
                @_9.performed -= m_Wrapper.m_ActiveActionsCallbackInterface.On_9;
                @_9.canceled -= m_Wrapper.m_ActiveActionsCallbackInterface.On_9;
            }
            m_Wrapper.m_ActiveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @JumpRelease.started += instance.OnJumpRelease;
                @JumpRelease.performed += instance.OnJumpRelease;
                @JumpRelease.canceled += instance.OnJumpRelease;
                @PlaceTrap.started += instance.OnPlaceTrap;
                @PlaceTrap.performed += instance.OnPlaceTrap;
                @PlaceTrap.canceled += instance.OnPlaceTrap;
                @_1.started += instance.On_1;
                @_1.performed += instance.On_1;
                @_1.canceled += instance.On_1;
                @_2.started += instance.On_2;
                @_2.performed += instance.On_2;
                @_2.canceled += instance.On_2;
                @_3.started += instance.On_3;
                @_3.performed += instance.On_3;
                @_3.canceled += instance.On_3;
                @_4.started += instance.On_4;
                @_4.performed += instance.On_4;
                @_4.canceled += instance.On_4;
                @_5.started += instance.On_5;
                @_5.performed += instance.On_5;
                @_5.canceled += instance.On_5;
                @_6.started += instance.On_6;
                @_6.performed += instance.On_6;
                @_6.canceled += instance.On_6;
                @_7.started += instance.On_7;
                @_7.performed += instance.On_7;
                @_7.canceled += instance.On_7;
                @_8.started += instance.On_8;
                @_8.performed += instance.On_8;
                @_8.canceled += instance.On_8;
                @_9.started += instance.On_9;
                @_9.performed += instance.On_9;
                @_9.canceled += instance.On_9;
            }
        }
    }
    public ActiveActions @Active => new ActiveActions(this);
    public interface IActiveActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnJumpRelease(InputAction.CallbackContext context);
        void OnPlaceTrap(InputAction.CallbackContext context);
        void On_1(InputAction.CallbackContext context);
        void On_2(InputAction.CallbackContext context);
        void On_3(InputAction.CallbackContext context);
        void On_4(InputAction.CallbackContext context);
        void On_5(InputAction.CallbackContext context);
        void On_6(InputAction.CallbackContext context);
        void On_7(InputAction.CallbackContext context);
        void On_8(InputAction.CallbackContext context);
        void On_9(InputAction.CallbackContext context);
    }
}
